name: Nodejs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "*/10 * * * *" # Executa a cada 5 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            gnupg \
            ca-certificates \
            apt-transport-https \
            xvfb \
            && sudo rm -rf /var/lib/apt/lists/*

      - name: Instalar Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - \
          && echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list \
          && sudo apt-get update \
          && sudo apt-get install -y google-chrome-stable \
          && sudo rm -rf /var/lib/apt/lists/*

      - name: Instalar dependências do Python
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Adicionar Key
        env:
          KEY: ${{ secrets.KEY }}
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          echo "$KEY" > key.pem
          echo "$CONFIG" > config

      - name: Instalar dependências do Node.js
        run: npm update && npm install

      - name: Adicionar ADDRESS em address.txt
        env:
          NANO_ADDRESS: ${{ secrets.NANO_ADDRESS }}
          NANO_ADDRESS_2: ${{ secrets.NANO_ADDRESS_2 }}
          NANO_ADDRESS_3: ${{ secrets.NANO_ADDRESS_3 }}
          NANO_ADDRESS_4: ${{ secrets.NANO_ADDRESS_4 }}
          NANO_ADDRESS_5: ${{ secrets.NANO_ADDRESS_5 }}
        run: |
          echo "$NANO_ADDRESS" > address.txt
          echo "$NANO_ADDRESS_2" > address_2.txt
          echo "$NANO_ADDRESS_3" > address_3.txt
          echo "$NANO_ADDRESS_4" > address_4.txt
          echo "$NANO_ADDRESS_5" > address_5.txt

      - name: Executar node index.js
        env:
          URL: ${{ secrets.URL }}
          URL_2: ${{ secrets.URL_2 }}
          URL_3: ${{ secrets.URL_3 }}
          HOST_PROXY: ${{ secrets.HOST_PROXY }}
          USER_PROXY: ${{ secrets.USER_PROXY }}
          SENHA_PROXY: ${{ secrets.SENHA_PROXY }}
          PORT_PROXY: ${{ secrets.PORT_PROXY }}
          HOST: ${{ secrets.HOST }}
          VNIC_ID: ${{ secrets.VNIC_ID }}
          COMPARTMENT_ID: ${{ secrets.COMPARTMENT_ID }}
        run: |
          xvfb-run --auto-servernum -- node --trace-warnings index.js

      - name: Atualiza screen.png
        env:
          SENHA_PDF: ${{ secrets.SENHA_PDF }}
        run: |
          sudo apt-get update && sudo apt-get install -y img2pdf qpdf
          img2pdf screen.png -o temp.pdf && qpdf --encrypt $SENHA_PDF $SENHA_PDF 256 -- temp.pdf screen.pdf && rm temp.pdf
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add screen.pdf || echo "Nada para adicionar"
          git commit -m "Atualiza screen.pdf" || echo "Nada para commitar"
          git push --quiet || echo "Falha no push, provavelmente conflito"
